version: "3.9"
services:
  db:
    image: postgres:16
    container_name: pruefungssystem-db
    environment:
      POSTGRES_USER: teamuser
      POSTGRES_PASSWORD: geheim
      POSTGRES_DB: softwareprojekt
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    restart: unless-stopped
